spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baby-way
    username: root
    password: 159357

  data:
    redis:
      host: localhost
      port: 6379
